TYPO3:
  Flow:
    persistence:
      backendOptions:
        driver:   pdo_mysql
        dbname:   %NEOS_DB_NAME%
        user:     %NEOS_DB_USER%
        password: %NEOS_DB_PASS%
        host:     %NEOS_DB_HOST%
        port:     %NEOS_DB_PORT%
