TYPO3:
  Flow:
    persistence:
      backendOptions:
        driver:   pdo_mysql
        dbname:   DB_NAME
        user:     DB_USER
        password: DB_PASSWORD
        host:     DB_HOST
        port:     DB_PORT
